<?php
/**
 * @category    design
 * @package     accessshop_lite_default
 * @copyright   Copyright (c) 2015 AccessShop Themes (http://www.accessshopthemes.com)
 ***
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar clearfix">
	<?php if( $this->isExpanded() ): ?>
        <div class="sorter">
        	<?php if($this->getLastPageNum()>1): ?>
                <p class="amount amount--has-pages">
                    <?php echo $this->__('%s-%s of %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
                </p>
            <?php else: ?>
                <p class="amount amount--no-pages">
                    <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
                </p>
            <?php endif; ?>
        	<div class="sort-by">
                <label><?php echo $this->__('Sort By') ?></label>
                <select onchange="setLocation(this.value)" title="<?php echo $this->__('Sort By') ?>">
                    <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                        <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                            <?php echo $this->__($_order) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <?php if($this->getCurrentDirection() == 'desc'): ?>
                    <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" class="sort-by-switcher sort-by-switcher--desc" title="<?php echo $this->__('Set Ascending Direction') ?>"><i class="fa fa-sort-amount-asc"></i></a>
                <?php else: ?>
                    <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" class="sort-by-switcher sort-by-switcher--asc" title="<?php echo $this->__('Set Descending Direction') ?>"><i class="fa fa-sort-amount-desc"></i></a>
                <?php endif; ?>
            </div>
            <div class="limiter">
                <label><?php echo $this->__('Show') ?></label>
                <select onchange="setLocation(this.value)" title="<?php echo $this->__('Results per page'); ?>">
                <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                    <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                        <?php echo $_limit ?>
                    </option>
                <?php endforeach; ?>
                </select>
            </div>
            <?php if( $this->isEnabledViewSwitcher() ): ?>
                <p class="view-mode">
                    <?php $_modes = $this->getModes(); ?>
                    <?php if($_modes && count($_modes)>1): ?>
                        <label><?php echo $this->__('View as') ?></label>
                        <?php foreach ($this->getModes() as $_code=>$_label): ?>
                            <?php if($this->isModeActive($_code)): ?>
                                <span title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><i class="fa <?php echo($_code=='grid')?"fa-th":"fa-th-list";?>"></i></span>
                            <?php else: ?>
                                <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><i class="fa <?php echo($_code=='grid')?"fa-th":"fa-th-list";?>"></i></a>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </p>
            <?php endif; ?>
            <?php echo $this->getPagerHtml() ?>
        </div>
    <?php endif; ?>
</div>
<?php endif ?>