<?php
/**
 * @category    design
 * @package     accessshop_lite_default
 * @copyright   Copyright (c) 2015 AccessShop Themes (http://www.accessshopthemes.com)
 */
?>
<div class="clear"></div>
<?php
$_productCollection = $this->getItemCollection()->getItems();
$_helper = $this->helper('catalog/output');
$i=0;
//echo count($_productCollection);
?>
<div class="upsell-prducts">
    <div class="best-sales-title">
        <h2>UPSELL PRODUCT(S)</h2>
        <div class="slidercontrols">
            <a class="prev" id="prev2" href="#">Prev</a>
            <a class="next" id="next2" href="#">Next</a>
        </div>
    </div>
    
    <div class="upsell-items">
        <?php if (!count($_productCollection)): ?>
            <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
        <?php else: ?>
            <div class="category-products list_carousel responsive">
                <?php $_collectionSize = count($_productCollection); ?>
                <?php
                $_columnCount = $this->getColumnCount();
                $count=0.2;
                ?>
                <ul class="products-grid carousel hover-effect" data-carousel-prev="#prev2" data-carousel-next="#next2">
                    <?php foreach ($_productCollection as $_product): ?>
                        <li class="wow flipInY item<?php if ($i == 0): ?> first<?php elseif ($i == ($_collectionSize-1)): ?> last<?php endif; ?>" data-wow-delay="<?php echo $count ?>s">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="productimage">
                                <img src="<?php echo $this->helper('catalog/image')->init($_product,'small_image')->resize(200,300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="imgresponsive" />
                                <?php
                                $specialPrice = number_format($_product->getFinalPrice(), 2);
                                $regularPrice = number_format($_product->getPrice(), 2);
                                if ($specialPrice != $regularPrice)
                                {
                                    ?><label class="sale-label">SALE</label><?php
                                }
                                ?>
                            </a>
                            <div class="product-desc-bestsales">
                                <h3 class="panel-title product-name">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>
                                </h3>
                                <?php echo $this->getPriceHtml($_product, true) ?>
                            </div>
                            <div class="display-onhover">
                                <div class="actions clearer">
                                    <?php if($_product->isSaleable()): ?>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="fa fa-shopping-cart"></i></span></span></button>
                                    <?php else: ?>
                                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                </div>
                                <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a title="<?php echo $this->__('Add to Wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><i class="fa fa-heart"></i></a></li>
                                    <?php endif; ?>
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                        <li>
                                            <a title="<?php echo $this->__('Add to Compare') ?>" href="<?php echo $_compareUrl ?>" class="link-compare"><i class="fa fa-link"></i></a></li>
                                        <?php endif; ?>
                                    </ul>
                            </div>
                        </li>
                    <?php 
                    $count+=0.5;
                    $i++; endforeach 
                    ?>
                </ul>
            </div>
        <?php endif; ?>
    </div>
    
</div>
<div class="clear"></div>