<?php
/**
 * @category    design
 * @package     accessshop_lite_default
 * @copyright   Copyright (c) 2015 AccessShop Themes (http://www.accessshopthemes.com)
 * 
 */
?>
<?php if ($this->getReviewsCount()): ?>
    <div class="ratings">
        <?php if ($this->getRatingSummary()):?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
            </div>
        <?php endif;?>
        <p class="rating-links">
            <a id="goto-reviews" href="#reviews"><?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?></a>
            <span class="separator">|</span>
            <a id="goto-reviews-form" href="#reviews"><?php echo $this->__('Add Your Review') ?></a>
        </p>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <p class="no-rating"><a id="goto-reviews-form" href="#review"><?php echo $this->__('Be the first to review this product') ?></a></p>
<?php endif; ?>
