<?php
/**
 * @category    design
 * @package     accessshop_lite_default
 * @copyright   Copyright (c) 2015 AccessShop Themes (http://www.accessshopthemes.com)
 *
 * Product view template
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">

    <div class="product-essential">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>

            <div class="row">
                <div class="product-img-column col-sm-5">
                    <?php echo $this->getChildHtml('media') ?>
                </div>
                <div class="product-shop col-sm-7">
                    <div class="product-name">
                        <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                    </div>
                    
                    <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                    
                    <?php if ($_product->getShortDescription()):?>
                        <div class="short-description">
                            <!--<h2><?php //echo $this->__('Quick Overview') ?></h2>-->
                            <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                        </div>
                    <?php endif;?>

                    <div class="product-details">
                        <?php echo $this->getChildHtml('alert_urls') ?>
                        <div class="product-type-data">
                            <?php echo $this->getChildHtml('product_type_data') ?>
                            <?php echo $this->getTierPriceHtml() ?>
                        </div>
                        <?php echo $this->getChildHtml('extrahint') ?>

                        <?php if (!$this->hasOptions()):?>
                            <div class="add-to-box">
                                <?php if($_product->isSaleable()): ?>
                                    <?php echo $this->getChildHtml('addtocart') ?>
                                    <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                        <span class="or"><?php echo $this->__('OR') ?></span>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php echo $this->getChildHtml('addto') ?>
                            </div>
                            <?php echo $this->getChildHtml('extra_buttons') ?>
                        <?php elseif (!$_product->isSaleable()): ?>
                            <div class="add-to-box">
                                <?php echo $this->getChildHtml('addto') ?>
                            </div>
                        <?php endif; ?>

                        <?php echo $this->getChildHtml('other');?>

                        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                            <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                        <?php endif;?>
                        <div style="display:inline-block; padding-right: 1200px; ">
                                                     </div>
                    </div>
                               
                </div>

                <div class="clearer"></div>
                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                <?php endif;?>
            </div>
            
        </form>
        <script type="text/javascript">
        //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                 form.action = url;
             }
             var e = null;
             try {
                this.form.submit();
            } catch (e) {
            }
            this.form.action = oldUrl;
            if (e) {
                throw e;
            }

            if (button && button != 'undefined') {
                button.disabled = true;
            }
        }
    }.bind(productAddToCartForm);

    productAddToCartForm.submitLight = function(button, url){
        if(this.validator) {
            var nv = Validation.methods;
            delete Validation.methods['required-entry'];
            delete Validation.methods['validate-one-required'];
            delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
        //]]>
    </script>
</div>

<div class="product-collateral">
        <?php /* foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
            <div class="box-collateral <?php echo "box-{$alias}"?>">
                <?php if ($title = $this->getChildData($alias, 'title')):?>
                <h2><?php echo $this->escapeHtml($title); ?></h2>
                <?php endif;?>
                <?php echo $html; ?>
            </div>
        <?php endforeach;*/?>
        <?php
        $customtab1 = Mage::getModel('cms/block')->load('custom-tab1');
        $customtab2 = Mage::getModel('cms/block')->load('custom-tab2');
        ?>
        
        <ul class="nav nav-tabs" role="tablist">
            <?php $i=0; foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
            <li class="<?php if($i==0){echo "active";}?>">
                <a data-toggle="tab" href="#<?php echo "box-{$alias}"?>">
                    <?php if ($title = $this->getChildData($alias, 'title')):?>
                        <?php echo ($title!='')?$title:ucwords($alias); ?>
                    <?php else:?>
                        <?php echo ucwords($alias); ?>
                    <?php endif;?>
                </a>
            </li>             
            <?php $i++; endforeach;?>
            <li><a data-toggle="tab" class="reviews" name="reviews-tab" href="#reviews">Reviews</a></li>
            <li><a data-toggle="tab" href="#product-tags">Tags</a></li>
            <li><a data-toggle="tab" href="#custom-tab1"><?php echo($customtab1->getTitle()!='')?$customtab1->getTitle():'Custom Tab 1';?></a></li>
            <li><a data-toggle="tab" href="#custom-tab2"><?php echo($customtab2->getTitle()!='')?$customtab2->getTitle():'Custom Tab 2';?></a></li>
        </ul>
        <div class="tab-content">
            <?php $i=0; foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
            <div id="<?php echo "box-{$alias}"?>" class="tab-pane fade in <?php if($i==0){echo "active";}?>">
                <?php echo $html; ?>
            </div>
            <?php $i++; endforeach;?>
            <div id="reviews" class="tab-pane fade in">
                <?php echo $this->getChildHtml('reviews'); ?>                     
            </div>
            <div id="product-tags" class="tab-pane fade in">
                <?php echo $this->getChildHtml('product_additional_data') ?>
            </div>
            <div id="custom-tab1" class="tab-pane fade in">
                <?php if($customtab1->getContent()!=''){echo $customtab1->getContent();}
                else{?>
                <h2>Custom Tab Content 1</h2>
                <p>Custom Variants and Options let you create product customization options and fields quickly and easily. Any product can have custom variants and options – this can be configured in its product configuration. Custom variants and options can be created for products as required or non-required options. They can affect the total price of the product by a fixed amount or percentage.
                    <br />
                    In other words, custom variants and options allow you to make products that are unique and individualized. Whether it’s a gift with a special message, a sweatshirt with custom embroidered text, or anything in between – possibilities are limitless.</p>
                    <?php }?>
                </div>
                <div id="custom-tab2" class="tab-pane fade in">
                    <?php if($customtab2->getContent()!=''){echo $customtab2->getContent();}
                    else{?>
                    <h2>Custom Tab Content 2</h2>
                    <p>Custom Variants and Options let you create product customization options and fields quickly and easily. Any product can have custom variants and options – this can be configured in its product configuration. Custom variants and options can be created for products as required or non-required options. They can affect the total price of the product by a fixed amount or percentage.
                        <br />
                        In other words, custom variants and options allow you to make products that are unique and individualized. Whether it’s a gift with a special message, a sweatshirt with custom embroidered text, or anything in between – possibilities are limitless.</p>
                        <?php }?>
                    </div>
                </div>
                <?php echo $this->getChildHtml('upsell_products') ?>
                <?php //echo $this->getChildHtml('product_additional_data') ?>
            </div>
        </div>
