<?php
/**
 * @category    design
 * @package     accessshop_lite_default
 * @copyright   Copyright (c) 2015 AccessShop Themes (http://www.accessshopthemes.com)
 *
 * Magento SuperXpress
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<div class="header-top">
    <div class="container">
        <div class="row">
            <div class="col-sm-5">
                <div class="left-header-top">
                    <?php echo $this->getChildHtml('block_header_links_top_left'); ?>
                    <?php echo $this->getChildHtml('store_language') ?>
                    <?php echo $this->getChildHtml('topContainer'); ?>
                </div>
            </div>
            <div class="col-sm-7 pull-right">
                <div class="right-header-top">
                    <div class="row">
                        
                        <div class="col-sm-12 text-right">
                            <?php echo $this->getChildHtml('block_header_links_right');?>
                            <?php echo $this->getChildHtml('topLinks');?>
                            <div class="top-cart"><?php echo $this->getChildHtml('top_cart'); ?></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">

    <div class="row">
        <div class="col-sm-4">
            <div class="logo">
                <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>">
                    <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
                </a>
            </div>
        </div>
        <div class="col-sm-8 pull-right">
            <div class="row">
                <div class="col-sm-12">
                    <span class="welcome">
                        <?php echo $this->getLayout()->getBlock('header')->getWelcome(); ?>    
                        </span>

                </div>
                <div class="col-sm-12 top-search">
                    <?php echo $this->getChildHtml('topSearch') ?>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Navigation -->
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-main-collapse">
                 <span class="sr-only">Toggle navigation</span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="javascript:void(0);">Menu</a>
           </div>
            <div class="collapse navbar-collapse navbar-main-collapse" id="navbar-main-collapse">
                <?php echo $this->getChildHtml('topMenu') ?>
            </div>
            </div>
        </div>
    </div>
</nav>