<?php
/**
 * @category    design
 * @package     accessshop_lite_default
 * @copyright   Copyright (c) 2015 AccessShop Themes (http://www.accessshopthemes.com)
 */
?>
<?php if ($this->getIsNeedToDisplaySideBar()):?>
<ul class="list-inline topcart">
    <li>
        <label for="top-cart">SHOPPING CART:</label>
        <span class="cart-sub-total">
			<?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal())?> 
			<?php echo Mage::app()->getStore()->getCurrentCurrencyCode();?>
		</span>
        <?php $_cartQty = $this->getSummaryCount() ?>
        <div class="top-shopping-cart">
        <i class="fa fa-shopping-cart"></i>
        <?php if ($_cartQty>0): ?>
            <?php if ($_cartQty==1): ?>
                <span class="amount">
                    <?php echo $this->__('<a href="%s">1</a>', $this->getUrl('checkout/cart')) ?>
                </span>
            <?php else: ?>
                <span class="amount">
                    <?php echo $this->__('<a href="%s">%s</a>', $this->getUrl('checkout/cart'), $_cartQty) ?>
                </span>
            <?php endif ?>            
        <?php else: ?>
            <span class="empty"><?php echo $this->__('0') ?></span>
        <?php endif ?>
        </div>
    </li>
</ul>
<div class="topcart-content" style="display:none;">
    
    <?php $_items = $this->getRecentItems() ?>
    <?php if(count($_items)>0): ?>
        <p class="block-subtitle"><?php echo $this->__('Recently added item(s)') ?></p>
        <ol id="cart-sidebar" class="mini-products-list">
            <?php foreach($_items as $_item): ?>
                <?php echo $this->getItemHtml($_item) ?>
            <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('cart-sidebar','none-recursive')</script>
        <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
        <div class="actions">
            <?php echo $this->getChildHtml('extra_actions') ?>
            <button type="button" title="<?php echo $this->__('View Cart')?>" class="button" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>')"><span><span><?php echo $this->__('View Cart') ?></span></span></button>
            <button type="button" title="<?php echo $this->__('Checkout')?>" class="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
        </div>
        <?php endif ?>
    <?php else: ?>
        <p class="block-subtitle"><?php echo $this->__('Your Cart Is Empty!') ?></p>
    <?php endif ?>
</div>
<?php endif; ?>