<?php
/**
 * @category    design
 * @package     accessshop_lite_default
 * @copyright   Copyright (c) 2015 AccessShop Themes (http://www.accessshopthemes.com)
 */
?>
<?php if ($this->getCheckout()->getStepData('billing', 'complete')): ?>
	<dt class="complete">
		<?php echo $this->__('Billing Address') ?><span class="changelink"> <span class="separator">|</span> <a
		href="#billing"
		onclick="checkout.changeSection('opc-billing'); return false;"><?php echo $this->__('Change') ?></a></span>
	</dt>
	<dd class="complete">
		<address><?php echo $this->getBilling()->format('html') ?></address>
	</dd>
<?php else: ?>
	<dt>
		<?php echo $this->__('Billing Address') ?>
	</dt>
<?php endif; ?>
