<?php
/**
 * @category    design
 * @package     accessshop_lite_default
 * @copyright   Copyright (c) 2015 AccessShop Themes (http://www.accessshopthemes.com)
 */
?>
<?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
	<dt class="complete">
		<?php echo $this->__('Payment Method') ?><span class="changelink"> <span class="separator">|</span> <a
		href="#payment"
		onclick="checkout.changeSection('opc-payment'); return false;"><?php echo $this->__('Change') ?></a></span>
	</dt>
	<dd class="complete">
		<?php echo $this->getPaymentHtml() ?>
	</dd>
<?php else: ?>
	<dt>
		<?php echo $this->__('Payment Method') ?>
	</dt>
<?php endif; ?>

