<?php
/**
 * @category    design
 * @package     accessshop_lite_default
 * @copyright   Copyright (c) 2015 AccessShop Themes (http://www.accessshopthemes.com)
 */
?>
<?php if(count($this->getStores())>1): ?>
        <ul class="language list-inline">
            <li class="parent current-language">
                <?php foreach ($this->getStores() as $_lang): ?>
                    <?php if($_lang->getId() == $this->getCurrentStoreId()):?>
                        <a href="javascript:void(0);" style="background-image:url('<?php echo $this->getSkinUrl('images/flags/flag_'.$_lang->getCode().'.png') ?>');background-repeat: no-repeat;padding-left:25px;">
                            <?php echo $this->escapeHtml($_lang->getName()) ?>
                            <span class="caret"></span>
                        </a>
                    <?php endif; ?>
                <?php endforeach; ?>
                <ul class="language-sub">
                    <?php foreach ($this->getStores() as $_lang): ?>
                        <?php if($_lang->getId() != $this->getCurrentStoreId()):?>
                            <li style="background-image:url('<?php echo $this->getSkinUrl('images/flags/flag_'.$_lang->getCode().'.png') ?>');background-repeat: no-repeat;padding-left:25px;">
                                <a href="<?php echo $_lang->getCurrentUrl() ?>">
                                    <?php echo $this->escapeHtml($_lang->getName()) ?>
                                </a>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </li>
         </ul>
<?php endif; ?>
